name: mi UPB Devops 2025 CICD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Node.js API image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app ./  # ruta a tu Dockerfile Node
      - name: Publish API image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

  build-web:
    runs-on: ubuntu-latest
    needs: build-api  
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Web image (Apache + index.html)
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/web:latest ./public-web
      - name: Publish Web image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/web:latest

  deploy-api:
    needs: build-api
    runs-on: [self-hosted]
    steps:
      - name: Pull API image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
      - name: Delete old API container
        run: docker rm -f nodejs-app-container || true
      - name: Run API container
        run: docker run -d -p 3000:3000 --name nodejs-app-container ${{ secrets.DOCKER_USERNAME }}/nodejs-app

  deploy-web:
    needs: build-web
    runs-on: [self-hosted]
    steps:
      - name: Pull Web image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/web:latest
      - name: Delete old Web container
        run: docker rm -f web-container || true
      - name: Run Web container
        run: docker run -d -p 80:80 --name web-container ${{ secrets.DOCKER_USERNAME }}/web:latest

